### ISSUE TITLE
Padronizar nomenclatura de pastas e arquivos

### ISSUE THREAD

**Issue by gabrielbdornas** [lab-mg/automatizacoes#19]
@Andrelamor, tenho reparado que alguns arquivos e pastas utilizamos hifens e outros underscores durante o processo de nomenclatura.

![image](https://github.com/lab-mg/automatizacoes/assets/49699290/797660d9-7404-44fc-b490-95374e1a24c5)

Além de deixar o repo sem padrão, sugiro trabalharmos sempre com o underscores pois o python pode apresentar alguns erros com hifens.

O que você acha?

**Comment by Andrelamor** [comment]
ok, vamos alterar nomes de pastas e arquivos para snake_case
