### ISSUE TITLE
Definir página modelo de robôs

### ISSUE THREAD

**Issue by gabrielbdornas** [lab-mg/automatizacoes#22]
- [x] Criação de partials.
- [x] Melhoria e simplificação de textos.
- [x] Vídeo na parte inicial da página.
- [x] Arquivo abreviations.
- [x] Caixas collapsible com mesma cor.
- [x] Definir aonde incluir e-mail do criador do robô.
- [x] Melhorar disposição vídeo

**Comment by gabrielbdornas** [comment]
Descobri [este issue](https://github.com/squidfunk/mkdocs-material/issues/492) que ajudou a resolver o problema do enquadramento dos vídeos.

**Comment by gabrielbdornas** [comment]
Acredito que precisamos validar a página.

- O texto está bom?
- Aonde incluir o nome do responsável pelo robô. Pensei em colocar apenas seu e-mail nos pedidos de ajuda.
- Alguma caixa hoje collapsable poderia ser aberta de maneira permanente, como o pedido de ajuda.
- O título das caixas collapsable estão bons?

**Comment by Andrelamor** [comment]
> Acredito que precisamos validar a página.
> 
> * O texto está bom?
> * Aonde incluir o nome do responsável pelo robô. Pensei em colocar apenas seu e-mail nos pedidos de ajuda.
> * Alguma caixa hoje collapsable poderia ser aberta de maneira permanente, como o pedido de ajuda.
> * O título das caixas collapsable estão bons?

@gabrielbdornas, sim os textos e títulos ficaram sucintos e claros; o nome

**Comment by Andrelamor** [comment]
## Nova aba para projetos da SCAP

@gabrielbdornas não falamos disso ontem, mas já tínhamos conversado a respeito da ideia de juntar os robôs do projeto da SCAP numa aba separada, lembra? 
Então, rascunhei uma ideia de view, mas pra não bagunçar, em vez de commitar, vou printar a imagem e deixar os arquivos na stagging area; quando puder, a gente avalia e implementa. 
Uma definição que adotei é a de que os robôs vivem na página https://lab-mg.github.io/automatizacoes/robos/ e são referenciados pra lá por hiperlink a partir de https://lab-mg.github.io/automatizacoes/projetos/scap/ (nova pasta/aba a ser criada)
![image](https://github.com/lab-mg/automatizacoes/assets/52294411/0a6e327b-f8ca-4e49-8033-a04bf6c1bd88)

**Comment by Andrelamor** [comment]
> ## Nova aba para projetos da SCAP
> @gabrielbdornas não falamos disso ontem, mas já tínhamos conversado a respeito da ideia de juntar os robôs do projeto da SCAP numa aba separada, lembra? Então, rascunhei uma ideia de view, mas pra não bagunçar, em vez de commitar, vou printar a imagem e deixar os arquivos na stagging area; quando puder, a gente avalia e implementa. Uma definição que adotei é a de que os robôs vivem na página https://lab-mg.github.io/automatizacoes/robos/ e são referenciados pra lá por hiperlink a partir de https://lab-mg.github.io/automatizacoes/projetos/scap/ (nova pasta/aba a ser criada) ![image](https://user-images.githubusercontent.com/52294411/277676463-0a6e327b-f8ca-4e49-8033-a04bf6c1bd88.png)

@gabrielbdornas para que Isa e Yan possam perceber melhor as possibilidades de visualização dos robôs criados no âmbito do projeto SCAP nas páginas deste repo, implementei a sugestão em https://lab-mg.github.io/automatizacoes/projetos/scap/

**Comment by Andrelamor** [comment]
@gabrielbdornas [o conteúdo das linhas 46 e 52 do texto-padrão do robô](https://github.com/lab-mg/automatizacoes/commit/8323bab8293937a3deb37c63130071ef366fa7c0#diff-7099fa9a82d5450c7b671eff7ac8ee8b9b55021deacc4b208441bf356f01243eR46) têm o mesmo objetivo, veja:
![image](https://github.com/lab-mg/automatizacoes/assets/52294411/bd0a4e6c-b645-4a52-9041-107be8f06cb3); sendo assim, entendo que é melhor deixar o texto solto em vez de encapsulado, para ficar mais visível, e também por já haver uma caixinha acima e outra abaixo.

**Comment by gabrielbdornas** [comment]
> ; sendo assim, entendo que é melhor deixar o texto solto em vez de encapsulado, para ficar mais visível (se é importante), e também por já haver uma caixinha acima e outra abaixo.

@Andrelamor, joia! Particularmente gosto mais do texto que está dentro da caixinha, que foi revisado com Lucas na última quinta. Já que ele é importante, o que acha de deixarmos a caixinha, mas sem o collapsable? Ou seja a caixinha ficaria sempre aberta, focando esta parte importante.

**Comment by Andrelamor** [comment]
> > ; sendo assim, entendo que é melhor deixar o texto solto em vez de encapsulado, para ficar mais visível (se é importante), e também por já haver uma caixinha acima e outra abaixo.
> 
> @Andrelamor, joia! Particularmente gosto mais do texto que está dentro da caixinha, que foi revisado com Lucas na última quinta. Já que ele é importante, o que acha de deixarmos a caixinha, mas sem o collapsable? Ou seja a caixinha ficaria sempre aberta, focando esta parte importante.

@gabrielbdornas solução interessante, mas penso que o texto dela não seria padrão, e sim o que pertence ao caso concreto do robô em questão

**Comment by Andrelamor** [comment]
o novo modelo de pastas em `/docs` foi aplicado para o robô do IGAM, faltam o do CAGEC e o da progressão SISAP; ainda assim, o primeiro ficou com os links quebrados para o txt do robô, amanhã vou revisar
