### ISSUE TITLE
Criar post sobre guia de estilo das páginas

### ISSUE THREAD

**Issue by gabrielbdornas** [lab-mg/automatizacoes#31]
@Andrelamor, lendo o #5 pensei em criar um post para o Guia de estilo das páginas. Isso englobaria, inclusive tags.

**Comment by gabrielbdornas** [comment]
@Andrelamor, post com [Guia de estilo de nossas páginas criado](https://lab-mg.github.io/automatizacoes/blog/guia-de-estilo-de-nossas-paginas/). Gostaria de saber se você concorda com todas as regras aí incluídas. Deixo bem claro que se trata de uma sugestão e qualquer sugestão será bem-vinda.

Aproveito para incluir [este commit](https://github.com/lab-mg/automatizacoes/commit/70460e43b011d8854e133dcac5d7e7a1a5a56ceb), como curiosidade, aonde fiz o teste para que a estrutura de um post fique em uma pasta, simplificando assim a organização dos arquivos.

**Comment by Andrelamor** [comment]
@gabrielbdornas isso podia ter sido combinado; o post 4 era conteúdo 'real'; o 3 também era, aplicação de uma tabela que está no repositório e vai ser utilizada no painel da página inicial

**Comment by gabrielbdornas** [comment]
> @gabrielbdornas isso podia ter sido combinado; o post 4 era conteúdo 'real'; o 3 também era, aplicação de uma tabela que está no repositório e vai ser utilizada no painel da página inicial.
> 
> Este issue foi aberto hoje, não havia sido discutido na reunião de planejamento que tivemos há dois dias. Enfim, como já está aplicado, não entendi que diferença faria uma sugestão minha. A minha sugestão inicial pra qualquer aspecto do repositório é confirmar/combinar previamente exclusão de conteúdo de autoria alheia.

@Andrelamor, perfeito! Acredito que você está com toda razão. Deveria ter alinhado antes com você minha intenção que seria:

- Melhorar a organização dos posts.
- Incluir a propriedade `draft: true` em posts ainda não finalizados. Com isso o post não aparecerá em [produção](https://lab-mg.github.io/automatizacoes/blog/) e sim em ambiente local [http://localhost:8000/](http://localhost:8000/).

Neste sentido, os posts deletados agora estão organizados dentro desta nova estrutura. 

[Continuo pedindo avaliação e alinhamento](https://github.com/lab-mg/automatizacoes/issues/31#issuecomment-1779738950) sobre as regras propostas, visando aprimorar a comunicação.

**Comment by Andrelamor** [comment]
o preview local deixou de funcionar após o conjunto de modificações de hoje: 

![Image](https://github.com/lab-mg/automatizacoes/assets/52294411/5da10400-c328-4869-bb32-26f4c0969eab)
