### ISSUE TITLE
Definir como guardaremos vídeos do portal

### ISSUE THREAD

**Issue by gabrielbdornas** [lab-mg/automatizacoes#4]
Uma sugestão poderá ser a criação de um canal no YouTube. Atualmente Lab-mg não possui nenhum canal.

Giovanna ficou de me retornar sobre isso porque, segundo ela:

> Se não me engano há uma diretriz de centralizar nesses canais para não dividir o público, daí por isso nunca criamos uma pra nós

Obs.: Atualmente links do sharepoint utilizados somente poderiam ser acessados para pessoas logadas e dentro da organização.

**Comment by gabrielbdornas** [comment]
@Andrelamor, Giovanna já está olhando a criação do Canal YouTube. Na próxima semana acredito que podemos dar um toque para ver o status da ação.

**Comment by Andrelamor** [comment]
## estratégias para aumentar compartilhamento de robôs (scripts e vídeos):
@gabrielbdornas @lab-mg/dcd uma dificuldade relatada pelo Lucas é a baixa adesão ao compartilhamento de vídeos:

> André, tive poucos retornos sobre vídeos e scripts de robôs. Acredito que somente com premiações, como destaques em redes sociais, ações institucionais, ações de comunicação (destaques do servidor e sua inovação na agência Minas, foto com governador...) ou concorrência por prêmio em $... a gente teria mais engajamento.

**Comment by gabrielbdornas** [comment]
@Andrelamor, por isso, e pela própria dificuldade já relatada em receber o formulário preenchido, acredito que esta é uma guerra quase perdida. Penso que a estratégia seja realmente buscar essas informações com o relatório de robôs mais executados emitido pela Intendência. Já conversamos com Henrique, responsável pelo contrato, e ele ficou de:

1. Incluir Lucas no painel destes relatórios, para uma exploração mais detalhada. 
2. Pedir uma reunião com a equipe Microsoft para entender melhor os relatórios e ver outras possibilidades como informações de robôs criados no desktop e não só na web. 

Você sabe se Lucas teve retorno dessas duas ações por parte do Henrique?

**Comment by gabrielbdornas** [comment]
Resposta Giovanna:

> Olá, bom dia! Eu conversei com a Edilene sobre essa possibilidade e ela avaliou que seria melhor centralizar tudo no YT da Seplag mesmo. Isso ocorre porque a gente já negou solicitações de criação de YT para outras áreas aqui da Seplag. Neste caso, vocês podem nos enviar todos os vídeos que quiserem, inclusive com títulos e descrições que querem colocar, e se devem ou não ser públicos, que a gente sobe e envia os links pra vocês!
