### ISSUE TITLE
gestão de vocabulário controlado para tags

### ISSUE THREAD

**Issue by Andrelamor** [lab-mg/automatizacoes#5]
Lista de categorias padronizada para classificar os robots, com, no máximo, duas tags de subcategoria para cada uma.

- Sugestões de fontes para estabelecermos a lista inicial(?) 
    - SEI
    - Carta de Serviços

**Comment by Andrelamor** [comment]
@gabrielbdornas modifiquei as tags para não duplicar os itens do catálogo em https://lab-mg.github.io/automatizacoes/tags/;

**Comment by Andrelamor** [comment]
[15:07] Lucas Melo Franco Fainblat

Sugestão para palavras-chave: TAGs relativas a sistemas com os quais os robôs interagem (SIAFI, SISAP, "Portal de Compras", SEI etc.); evitar TAGs com duas palavras (usar "SISAP", não "ferramentas - sisap"); usar duas TAGs para temas múltiplos, não uma só (usar "compras", "portal de compras"; ou "financeiro", "siafi" ao invés de "financeiro - siafi")

[15:08] Lucas Melo Franco Fainblat

Robôs de treinamento são sempre bons a gente registrar com TAG "treinamento" --> preferencialmente buscar algum outro termo como "treinamento SIGES" ou "treinamento seplag", pra diferenciar de um termo que porventura possa surgir envolvendo outros "treinamentos".

**Comment by gabrielbdornas** [comment]
@Andrelamor , que tal criamos um post na página do blog indicando boas práticas para criação de uma tag?
