### ISSUE TITLE
Problema no final das páginas, após comentários - Posts do Blog

### ISSUE THREAD

**Issue by gabrielbdornas** [lab-mg/automatizacoes#50]
@Andrelamor, navegando em posts do blog hoje encontrei a seguinte falha:

![image](https://github.com/lab-mg/automatizacoes/assets/49699290/08cffc01-0021-463a-abfc-685afe0b5e45)

Acessei dois posts diferentes e o problema foi igual.

**Comment by Andrelamor** [comment]
@gabrielbdornas achei a fonte do problema e no meu local deu certo a retirada das logos, veja aí no teu pfv...branch https://github.com/lab-mg/automatizacoes/compare/review-landing-page-lucas
