### ISSUE TITLE
depoimentos para a landing page

### ISSUE THREAD

**Issue by Andrelamor** [lab-mg/automatizacoes#56]
- [x] Alexander(Iepha]
- [x] Gabi (SCAP)
- [x] André (Trilhas)

------
## Comentário do @lucasfainblat:

@Andrelamor sugiro colocar a ordem: André, Gabi, Alexander... Se precisarmos de "foto bonitinha" ou descolada, eu tento pedir ao André. Mas o depoimento dele está sensacional!

Se colocar no portal, já dá pra fechar o issue. Quero mostrar pras meninas na segunda e aguardar comentários, porque desconfio que o ideal seja que condensemos os comentários em frases de impacto... Mas 🎵 _deixa acontecer naturalmente_  🎶

**Comment by Andrelamor** [comment]
Alexander (Iepha)
Dados

Nome: ALEXANDER MARAIR FERREIRA
Cargo: TÉCNICO DE GESTÃO, PROTEÇÃO E RESTAURO.
Órgão: IEPHA – MG
Unidade de exercício: GERÊNCIA DE RECUROS HUMANOS.
Projetos: Fluxos de cadastros no SISAP - Sistema de folha de pagamento e no SEI – Sistema Eletrônico de Informações.

Depoimento:

Com a implantação do projeto piloto de automatização de processos na Gerência de Recursos Humanos do IEPHA pelo Automatiza.MG, tivemos a oportunidade de conhecer o Power Automate, que nos ajudou na redução do tempo gasto em tarefas manuais e repetitivas, liberando a equipe para se concentrar em tarefas mais importantes.

A ferramenta comunica muito bem com diversos aplicativos e programas, com segurança e eficiência, ajudando na economia de recursos e tempo de espera para os públicos interno e externo. Em breve, novos fluxos poderão ser criados continuamente, no intuito de facilitar e desburocratizar os processos no serviço público, impactando diretamente na qualidade do trabalho.

**Comment by lucasfainblat** [comment]
> Alexander (Iepha) Dados

Segue a foto do Alexander:
![foto do Alexander](https://github.com/lab-mg/automatizacoes/assets/153224852/6bd9fe09-ae88-4d79-84fd-5a9cc7d50a69)

**Comment by lucasfainblat** [comment]
# Depoimento 2: Gabi (SCAP)

## Dados

Nome: **Gabriella Priscila Martins Marcelino**
Cargo: **equipe técnica**
Órgão: **SEPLAG**
Unidade de exercício: **Diretoria Central de Controle e Modernização do Pagamento de Pessoal - DCMPP** da Superintendência Central de Administração de Pessoal - SCAP.
Projetos: inserção de óbitos no SISAP; consulta emissão de certidões de óbito.

## Depoimento

Aqui a gente utiliza o Power Automate para a inserção de óbitos no Sistema de Administração de Pessoal (SISAP), com o objetivo de prevenir que sejam efetivados pagamentos para servidores falecidos. Esse serviço é muito importante, pois em caso de qualquer eventualidade, pagamentos irregulares podem ser equivocadamente programados, prejudicando os cofres públicos. Por conta da complexidade dos processos e de sua relevância, e considerando que há picos de demanda em períodos de pagamento de folha de pessoal, muitas vezes a equipe era obrigada a trabalhar para além do horário de expediente, ou até mesmo nos finais de semana!

**A automatização de processos via Power Automate conseguiu dar fôlego à equipe, pois agilizou significativamente o tempo exigido para completar o serviço, além de elevar o nível de sucesso, diminuindo o risco de erro. Com isso, houve aumento do bem-estar dos servidores!**

Além disso, a automatização de processos viabilizou que a gente desse mais atenção a outras atividades, racionalizando os nossos esforços e reduzindo o retrabalho. Por exemplo, havia um passivo de quase 6 mil pedidos de estornos bancários que precisávamos viabilizar para sanar pagamentos passados feitos por equívoco. A consulta e emissão automatizadas de certidões ou informes de óbito diminuiu consideravelmente esse passivo.

## Foto

![WhatsApp Image 2024-01-03 at 12 06 11](https://github.com/lab-mg/automatizacoes/assets/153224852/9723e4c6-50bd-47c9-aaa6-cfe5d13ab7d4)

**Comment by Andrelamor** [comment]
> # Depoimento 2: Gabi (SCAP)
> ## Dados
> Nome: **Gabriella Priscila Martins Marcelino** Cargo: **equipe técnica** Órgão: **SEPLAG** Unidade de exercício: **Diretoria Central de Controle e Modernização do Pagamento de Pessoal - DCMPP** da Superintendência Central de Administração de Pessoal - SCAP. Projetos: inserção de óbitos no SISAP; consulta emissão de certidões de óbito.
> 
> ## Depoimento
> Aqui a gente utiliza o Power Automate para a inserção de óbitos no Sistema de Administração de Pessoal (SISAP), com o objetivo de prevenir que sejam efetivados pagamentos para servidores falecidos. Esse serviço é muito importante, pois em caso de qualquer eventualidade, pagamentos irregulares podem ser equivocadamente programados, prejudicando os cofres públicos. Por conta da complexidade dos processos e de sua relevância, e considerando que há picos de demanda em períodos de pagamento de folha de pessoal, muitas vezes a equipe era obrigada a trabalhar para além do horário de expediente, ou até mesmo nos finais de semana!
> 
> **A automatização de processos via Power Automate conseguiu dar fôlego à equipe, pois agilizou significativamente o tempo exigido para completar o serviço, além de elevar o nível de sucesso, diminuindo o risco de erro. Com isso, houve aumento do bem-estar dos servidores!**
> 
> Além disso, a automatização de processos viabilizou que a gente desse mais atenção a outras atividades, racionalizando os nossos esforços e reduzindo o retrabalho. Por exemplo, havia um passivo de quase 6 mil pedidos de estornos bancários que precisávamos viabilizar para sanar pagamentos passados feitos por equívoco. A consulta e emissão automatizadas de certidões ou informes de óbito diminuiu consideravelmente esse passivo.
> 
> ## Foto
> ![WhatsApp Image 2024-01-03 at 12 06 11](https://private-user-images.githubusercontent.com/153224852/294013184-9723e4c6-50bd-47c9-aaa6-cfe5d13ab7d4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTY4MzgsIm5iZiI6MTcwNDMxNjUzOCwicGF0aCI6Ii8xNTMyMjQ4NTIvMjk0MDEzMTg0LTk3MjNlNGM2LTUwYmQtNDdjOS1hYWE2LWNmZTVkMTNhYjdkNC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDNUMjExNTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDkxNmVlNTk5NDhjOWQyYWMzOWJlM2UxNDBmNTY4ZGVmZjZmZjZlYTZmNmJhMDQ1MWFkODU4NTcxMjU1ZTQ5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wyVilUmDFY1p53i8JpeIVgPjem0FTzykrJBAXVCd-jw)

@lucasfainblat massa, mas a Gabi não pode nos enviar uma foto somente de rosto como o Alexander?

**Comment by Andrelamor** [comment]
![gabi-scap](https://github.com/lab-mg/automatizacoes/assets/52294411/96b84da4-9b54-4921-8e3a-b56f051b6bbd)

**Comment by lucasfainblat** [comment]
# Depoimento 3: André (Trilhas)

## Dados

Nome Completo: 
•⁠  ⁠⁠ Cargo:  da Secretaria de Estado de Educação 
• Unidade de lotação: Coordenação de Educação Profissional/Superintendência de Políticas Pedagógicas - SEE/SPP

Nome: **André Henrique Marques da Silva**
Cargo: **Coordenador Adjunto Qualifica Mais e Ponto Focal do Projeto Trilhas de Futuro**
Órgão: **SEE**
Unidade de exercício: **Superintendência de Políticas Pedagógicas - SPP**
Projetos: 

## Depoimento

Gostaria de expressar minha profunda satisfação e reconhecimento pelos **resultados extraordinários** alcançados por meio da implementação da automatização em nossa coordenação. A iniciativa não apenas superou nossas expectativas, mas também provocou um impacto transformador em diversas áreas. Inicialmente, a automatização se revelou como uma peça-chave nas demandas, **otimizando processos, identificando oportunidades que antes passavam despercebidas**. Essa eficiência operacional proporcionou uma visão mais abrangente e estratégica para a gestão de recursos. Além disso, **a notável agilidade introduzida pelo projeto não apenas economizou tempo, mas também permitiu uma alocação mais eficiente dos recursos humanos**, resultando na liberação de servidores para as demais atividades do setor, contribuindo significativamente para o **crescimento e desenvolvimento de outras áreas dentro da coordenação**. Gostaria de ressaltar e reconhecer o profissionalismo exemplar da equipe do Automatiza.MG, na pessoa do servidor Klécius, que esteve aqui durante todo o processo de implementação do projeto de automatização: sua dedicação incansável, suas habilidades técnicas notáveis e o seu comprometimento com a excelência foram fundamentais para o sucesso dessa iniciativa. Em suma, o projeto de automatização não apenas atendeu, mas **superou nossas expectativas**, proporcionando resultados tangíveis e impactos positivos em várias frentes. Expresso meu profundo agradecimento à equipe envolvida por seu comprometimento, expertise e sua dedicação na condução desse projeto tão significativo para o sucesso organizacional. Estamos ansiosos para continuar explorando novas possibilidades e avançar em conjunto na busca pela excelência.

## Foto

![fotoandre](https://github.com/lab-mg/automatizacoes/assets/153224852/991e045a-98e7-4064-ba7e-a645d7650ad6)

**Comment by Andrelamor** [comment]
@gabrielbdornas vou atualizar a foto e o depoimento do André, e reordenar de acordo com a sugestão do @lucasfainblat , num Pull Request para o @YanVieira1905
