### ISSUE TITLE
proteção da confidencialidade de eventuais informações sensíveis ou pessoais nos códigos compartilhados 

### ISSUE THREAD

**Issue by Andrelamor** [lab-mg/automatizacoes#6]
Página de cada robô somente será publicada se o autor do protótipo oficializar a anuência em texto-padrão (consulta @patrickciampi).

**Comment by Andrelamor** [comment]
## Disclaimer (página à parte)

[exemplo de não-garantia do código](https://github.com/pnp/powerautomate-samples/tree/main/samples/graph_api_in_power_bi#disclaimer): 
`THIS CODE IS PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.`

**Comment by gabrielbdornas** [comment]
@Andrelamor, acredito que #12 está relacionado.

**Comment by Andrelamor** [comment]
> @Andrelamor, acredito que #12 está relacionado.

@gabrielbdornas de fato, o disclaimer/termo de uso/anuência em produção para suprir a questão do #12 deve considerar trecho sobre proteção de dados; vou fechar este e colocar lá no outro exemplos de termos
