### ISSUE TITLE
descrever fluxo dos protótipos dos robôs dos treinamentos de setembro e outubro

### ISSUE THREAD

**Issue by Andrelamor** [lab-mg/automatizacoes#7]
@gabrielbdornas 
Pensei em descrever mais ou menos um fluxo sequencial das ações e uma tabela com os nomes dos comandos/instruções, https://github.com/lab-mg/mapeamento-SCAP/blob/main/prep-fluxo.md

Referência: https://github.com/pnp/powerautomate-samples/tree/main/samples/ProjectForTheWeb-Provisioning#project-for-the-web---provision-a-project 

- [x] 28/09: consulta portal Compras: https://lab-mg.github.io/automatizacoes/robos/consulta_situacao_fornecedores/#funcoes-desenvolvidas-pelo-prototipo (sem loop e if)
- [x] 05/10: progressão SISAP https://lab-mg.github.io/automatizacoes/robos/progressao_servidores/#funcoes-desenvolvidas-pelo-prototipo
- [x] 11/10: consulta outorgas IGAM

**Comment by Andrelamor** [comment]
- [ ] 28/09: consulta portal Compras
- [ ] 05/10: progressão SISAP

**Comment by gabrielbdornas** [comment]
> Pensei em descrever mais ou menos um fluxo sequencial das ações e uma tabela com os nomes dos comandos/instruções, https://github.com/lab-mg/mapeamento-SCAP/blob/main/prep-fluxo.md

@Andrelamor, gostei bastante da ideia. **Acho que é melhor de entender do que um texto corrido**. Só temos que analisar como ficará para fluxos muito grande. Como sugestão podemos pensar em um texto bem resumido e abaixo uma "caixinha que abre e fecha" igual fizemos com o código fonte:

![image](https://github.com/lab-mg/automatizacoes/assets/49699290/955da410-0988-496a-a414-4060db62575d)

O que acha?

**Comment by Andrelamor** [comment]
ideia: usar uma sintaxe similar à tripla de grafos do conhecimento para facilitar a descrição de cada ação do fluxo;
 exemplo de grafo de conhecimento em triplas em https://www.youtube.com/watch?v=SSwcncQiJ0g

**Comment by Andrelamor** [comment]
dificuldades e pontos de cuidado ao escrever o fluxo:
1. sintaxe específica do mermaid (graph TD): melhor escrever um passo de cada vez (demora bastante mais para ver o resultado no site estático);
2. descrever como ponto de vista humano tira da ordem o fluxo tal qual está no Power Automate;
3. uma ação do fluxo do ponto de vista humano pode ter mais de uma no programa Automate (ex.: acessar menu em site = mover mouse, enviar teclas, aguardar conteúdo...)
4. descrever como ponto de vista do robô dificulta a compreensão para quem nunca viu ou tesou o fluxo
5. uma única ação do power automate pode descrever mais de uma etapa (ex.: capturar tela consulta e salvar na pasta criada; ler coluna planilha e armazenar em variável criada)

**Comment by Andrelamor** [comment]
> ideia: usar uma sintaxe similar à tripla de grafos do conhecimento para facilitar a descrição de cada ação do fluxo; exemplo de grafo de conhecimento em triplas em https://www.youtube.com/watch?v=SSwcncQiJ0g

Ao tentar fazer o fluxo do robô de consulta ao CAGEC/CAFIMP, percebi que essa ideia acima fica excessivamente rebuscada tendo em vista as dificuldades de adaptação à sintaxe e escrita do fluxo; então estou concluindo ser desnecessária esse rigor de escrita para o momento. Uma estrutura simples 'ação (verbo) --> objeto' dá pra ser suficientemente bem escrita e informativa.

**Comment by gabrielbdornas** [comment]
> Ao tentar fazer o fluxo do robô de consulta ao CAGEC/CAFIMP, percebi que essa ideia acima fica excessivamente rebuscada tendo em vista as dificuldades de adaptação à sintaxe e escrita do fluxo; então estou concluindo ser desnecessária esse rigor de escrita para o momento. Uma estrutura simples 'ação (verbo) --> objeto' dá pra ser suficientemente bem escrita e informativa.

@Andrelamor, tendo em vista o relatado aqui, podemos fechar esse issue?

**Comment by Andrelamor** [comment]
> > Ao tentar fazer o fluxo do robô de consulta ao CAGEC/CAFIMP, percebi que essa ideia acima fica excessivamente rebuscada tendo em vista as dificuldades de adaptação à sintaxe e escrita do fluxo; então estou concluindo ser desnecessária esse rigor de escrita para o momento. Uma estrutura simples 'ação (verbo) --> objeto' dá pra ser suficientemente bem escrita e informativa.
> 
> @Andrelamor, tendo em vista o relatado aqui, podemos fechar esse issue?

@gabrielbdornas de acordo
